Metrics/CyclomaticComplexity:
  Enabled: false

Style/ParenthesesAroundCondition:
  ExcludeTernary: false
  AllowSafeAssignment: true

Naming/BlockParameterName:
  Enabled: false

Naming/QueryBoolMethods:
  Enabled: false

Style/WhileTrue:
  Enabled: false
