name: Specs

on:
  push:
    branches: ["**"]
  pull_request:
    branches: [master]
  workflow_dispatch:
jobs:
  specs:
    runs-on: ubuntu-latest
    steps:
      - name: Download source
        uses: actions/checkout@v6.0.2
      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1.9.2
      - name: Run tests
        run: crystal spec
